apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: w0sy0q99m-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: w0sy0q99m-go 
  name: w0sy0q99m-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: w0sy0q99m-go 
